### ISSUE TITLE
Спам ркон подключений в консоли

### ISSUE THREAD

**Issue by WataLaker37821** [EasyDonate/EasyPayments#11]
[16:25:38 INFO]: Thread RCON Client /193.32.248.203 started
[16:25:38 INFO]: Thread RCON Client /193.32.248.203 shutting down

Подозрение что это может быть вызвано плагином EasyPayments, не могу быть уверен, прикрепляю лог сервера за сегодня
[latest.log](https://github.com/EasyDonate/EasyPayments/files/12514157/latest.log)

**Comment by WataLaker37821** [comment]
Возможно это может еще быть вызвано плагином VotingPlugin, не уверен

**Comment by SoKnight** [comment]
Добрый день.
Плагин EasyPayments абсолютно не использует протокол RCON в каком-либо виде, а выдача покупок происходит совсем иным путём. Вам стоит проанализировать поведение других установленных плагинов, наш здесь явно не при чём.
Если Вас беспокоят неизвестные подключения, то Вы можете сменить пароль для доступа по RCON или выключить его.
