### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Derim16** [EasyDonate/EasyPayments#12]
![image](https://github.com/EasyDonate/EasyPayments/assets/87705209/7adb9fde-2ac2-492b-989e-3060aab6e355)

Добрый день. Что это значит? Возможно, я конечно ошибаюсь, но судя по действиям - похоже на взлом. Не подскажите,  как можно решить данную проблему?

**Comment by SoKnight** [comment]
Добрый день.
Какие-либо методы подделки сообщений о новых событиях не могут работать из-за особенности реализации. Протокол обмена сообщениями между плагином и EasyDonate API надёжно защищён.
Рекомендую Вам детально изучить список команд, которые Вы установили для товаров. Возможно, что-то тестировали и забыли убрать, или просто Вы не один в команде, и это сделал кто-то другой.
