### ISSUE TITLE
Repository 403

### ISSUE THREAD

**Issue by DxrkCat** [EasyDonate/EasyPayments#14]
[ERROR] Failed to execute goal on project v1_8_R1: Could not resolve dependencies for project ru.easydonate.easypayments:v1_8_R1:jar:2.2.2: Failed to collect dependencies at org.spigotmc:spigot:jar:1.8-SNAPSHOT: Failed to read artifact descriptor for org.spigotmc:spigot:jar:1.8-SNAPSHOT: Could not transfer artifact org.spigotmc:spigot:pom:1.8-SNAPSHOT from/to easylauncher (https://repo.easylauncher.org/repository/spigot-builds/): Authorization failed for https://repo.easylauncher.org/repository/spigot-builds/org/spigotmc/spigot/1.8-SNAPSHOT/spigot-1.8-SNAPSHOT.pom 403 Forbidden -> [Help 1

**Comment by SoKnight** [comment]
This issue should be fixed in upcoming update v2.3.
