### ISSUE TITLE
Двойная выдача товара в большинстве случаев

### ISSUE THREAD

**Issue by Amitexing** [EasyDonate/EasyPayments#2]
Большая часть наших покупок сопровождается тем, что донат выдается два раза. Если в случае привилегии это не страшно, то с двойной выдачей валюты начинаются большие проблемы. Насколько мне известно, такой проблемы с RCON выдачей нет, скорее всего проблема в обработке данных из бд. 
![image](https://user-images.githubusercontent.com/38596040/207799177-c41fe96d-d484-4292-8847-99aa2a975165.png)

**Comment by SoKnight** [comment]
Добрый день, @Amitexing.
Пожалуйста, предоставьте некоторые сведения о серверном окружении плагина для лучшего понимания ситуации:
- Операционная система / Версия
- Ядро сервера / Версия игры
- Версия EasyPayments
- Скриншот `/ep info`
- Состояние режима корзины (`plugins/EasyPayments/config.yml` > `use-shop-cart`)

**Comment by Amitexing** [comment]
1) Debian 11 1.19.2
2) Paper 1.19.2
3) EasyPayments-2.0.7
4) ![image](https://user-images.githubusercontent.com/38596040/207862253-da2c6d73-57a7-45cd-b16e-7ce8c0981703.png)
5) use-shop-cart: true

**Comment by SoKnight** [comment]
Попробуйте воспроизвести баг повторно, перед этим включив отладочные логи в конфиге (`logging` > `debug`)
Если получится, прикрепите логи к ответу на этот комментарий или [отправьте мне их лично](https://vk.me/soknight).

**Comment by SoKnight** [comment]
Если возможно, отправьте также снимок базы данных, если внешняя MySQL, или `plugins/EasyPayments/database.db`, если SQLite. Достаточно лишь таблиц:
- `easypayments_customers`
- `easypayments_payments`
- `easypayments_purchases`
