### ISSUE TITLE
Поддержка 1.19.3 для плагина

### ISSUE THREAD

**Issue by cubelius** [EasyDonate/EasyPayments#3]
Хотелось бы видеть её. 1.19.3 уже давно вышла, а выдача товаров по плагину, к сожалению, не работает.

**Comment by SoKnight** [comment]
Поддержка 1.19.3 уже давно готова.
Дело в том, что мы ждем дополнительной информации по поводу редкого бага, который хотелось бы исправить в предстоящем обновлении. Если она не появится в течение нескольких дней - мы выложим обновление без этого исправления, но с поддержкой 1.19.3.

**Comment by cubelius** [comment]
Можно было опубликовать версию плагина с пометкой dev, к примеру. Ну а так спасибо за информацию!
