### ISSUE TITLE
Поддержка ядра 1.19.3 purpur

### ISSUE THREAD

**Issue by TheAmazingAnimal** [EasyDonate/EasyPayments#4]
Обновил недавно ядро сервера на новую версию - но плагин выдает при старте с ним ошибку.
![image](https://user-images.githubusercontent.com/94377285/215111845-ec471646-4e8d-4888-b6c9-471e08fe6123.png)
Вроде как ошибка связана именно с тем, что версия ядра 1.19.3
Версия плагина стоит самая последняя - 2.0.8

**Comment by SoKnight** [comment]
Добрый день.

Попробуйте загружать плагин штатными методами - перезапуском сервера, а не сторонним ПО вроде PlugMan...
В следующий раз любые сообщения об ошибках, свидетельствующих о загрузке плагина сторонним ПО, будут проигнорированы, т.к. это не наша ответственность.

Ошибка связана с отсутствием шаблона конфига внутри JAR файла.
Вы точно ничего не изменяли внутри и скачивали плагин с официальных источников?

Официальными источниками являются:
- Раздел [релизов](https://github.com/EasyDonate/EasyPayments/releases) данного репозитория
- [EasyDonate](https://easydonate.ru)
- [Страница на SpigotMC](https://www.spigotmc.org/resources/easypayments.100793/)
- [Ветка на форуме](https://forum.easydonate.ru/d/117-mc-easypayments-alternativnyy-sposob-vydachi-tovarov)

**Comment by TheAmazingAnimal** [comment]
> 

Как скриншот приложена повторная перезагрузка через plugman. Сам плагин несколько раз пытался запустить через обычные перезагрузки сервера. JAR файл плагина не подвергался изменениям и работал корректно до обновления ядра

**Comment by SoKnight** [comment]
Провёл тестовый чистый запуск на актуальной сборке Purpur, всё хорошо.
Закрываю issue, ссылаясь на возможный запуск на сборке ядра с ошибкой на Вашей стороне.
Если проблема ещё актуальна - попробуйте обновиться.

![image](https://user-images.githubusercontent.com/46436573/215323677-c80fad4c-f694-4e67-bc42-460b79592367.png)
