### ISSUE TITLE
Playcholder

### ISSUE THREAD

**Issue by WerNetq** [EasyDonate/EasyPayments#5]
Сделайте плейсхолдер для топ донатеров а то я пользуюсь табличками и  каждый раз их надо менять

**Comment by SoKnight** [comment]
Добрый день.
Опишите, пожалуйста, конкретнее - какие плейсхолдеры Вы хотите видеть?
Как они должны прописываться, что отображать, и каким поведением обладать?
Также, на базе какого API стоит добавлять их поддержку - PlaceholderAPI или MWdVPlaceholders

**Comment by WerNetq** [comment]
PlaceholderAPI и должно отображаться скока игрок денег задонатил а не раз

**Comment by WerNetq** [comment]
А прописываться это я не знаю. Придумайте на вашу фонтазию просто сделайте пожалуйста
