### ISSUE TITLE
И где на 1.20?

### ISSUE THREAD

**Issue by BeDanGames** [EasyDonate/EasyPayments#8]
Говорили что будет 12 или 13 числа

**Comment by SoKnight** [comment]
Снова здравствуйте.
Это не площадка для чата, чтобы каждый день создавать новый Issue и спрашивать о дате выпуска обновления...
Ваши новые Issues с подобным вопросом в дальнейшем будут проигнорированы и закрыты сразу же.

Обновление было готово ещё 2 дня назад, но по причине загруженности команды разработчиков, не могло быть опубликовано за это время. Надеюсь, сегодня вечером оно будет опубликовано.

**Comment by BeDanGames** [comment]
Хорошо
